# Grafana Prometheus Datasource
# Project Bunyan - Foundation Stream

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://foundation-prometheus:9090
    isDefault: true
    editable: true

